### ISSUE TITLE
working in localhost but when published not working on dev env

### ISSUE THREAD

**Issue by aaayushishah** [agilgur5/react-signature-canvas#103]
Version I am using is  "react-signature-canvas": "^1.0.6",
React Versions

    "react": "^18.2.0",
    "react-dom": "^18.2.0",

**Comment by agilgur5** [comment]
You're going to need to provide a lot more information than that. There are several public demos that work and have worked for years.

Without a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example), there is not really anything actionable here.
