### ISSUE TITLE
Question // Add rgba value to penColor

### ISSUE THREAD

**Issue by SimonPaidla** [agilgur5/react-signature-canvas#108]
Hello everyone,

I have the following problem: I would like to use a transparent pen color to highlight texts (e.g., `rgba(255,0,0,0.3)`). As shown in the image, the bottom two lines (with rgba color value) do not deliver the desired result. Unfortunately, I couldn't gather from the documentation whether and how I can solve the problem myself, which is why I'm asking here.

- Is there an option to prevent these dots from appearing when using transparent color (example line 2/3 from the image)?
- Is there an option to prevent the lines from becoming "thicker" when redrawing with transparent color? (example line 3 from the image)

Thank you in advance for your help.
<img width="842" alt="Bildschirmfoto 2024-07-31 um 11 41 02" src="https://github.com/user-attachments/assets/0afae008-9f94-4b14-bce4-16b7b5756874">

**Comment by agilgur5** [comment]
For reference, the upstream issue is https://github.com/szimek/signature_pad/issues/780
