### ISSUE TITLE
Add TypeScript declaration file

### ISSUE THREAD

**Issue by BlessMyCode** [agilgur5/react-signature-canvas#21]
Can you add a typeScript declaration file in the project plz?
like this #5 but an updated version

**Comment by agilgur5** [comment]
I don't have experience with TypeScript, so I'm not confident in my ability to maintain a declaration file at this time. If there were a contributor who could maintain it, then I'd be okay with that, but otherwise I think a third-party typing makes more sense at this time.

As `signature_pad` recently did a re-write to TypeScript, I would like to do that at some point as well (and could potentially re-use `signature_pad`'s types that way), but I don't have a timeline for that right now.

**Comment by chillitom** [comment]
I've submitted a PR with definitions.

In the meantime I've dropped a file in my source repo `SignatureCanvas.d.ts` with the following definition:

```typescript
declare module 'react-signature-canvas' {
    // signature_pad's props
    export interface IOptions {
        dotSize?: number | (() => number);
        minWidth?: number;
        maxWidth?: number;
        minDistance?: number;
        backgroundColor?: string;
        penColor?: string;
        throttle?: number;
        velocityFilterWeight?: number;
        onBegin?: (event: MouseEvent | Touch) => void;
        onEnd?: (event: MouseEvent | Touch) => void;
    }

    // props specific to the React wrapper
    export interface SignatureCanvasProps extends IOptions {
        canvasProps: any;
        clearOnResize: boolean;
    }

    export default class SignatureCanvas extends React.Component<SignatureCanvasProps> {}
}
```

**Comment by ksocha** [comment]
I've created a PR to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) as discussed in #25 

[https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41396](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41396)

**Comment by agilgur5** [comment]
[`@types/react-signature-canvas`](https://www.npmjs.com/package/@types/react-signature-canvas) is now published thanks to @ksocha !! 🎉 🎉 
Please file any type issues with those unofficial third-party type definitions at [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).

Will be locking this now as a tracking issue. A TS re-write is in progress (https://github.com/agilgur5/react-signature-canvas/pull/25#issuecomment-562713553) so official internal TS support is planned for the v1.x release of `react-signature-canvas`, at which point `@types/react-signature-canvas` will no longer be necessary and will be deprecated.

**Comment by kmbro** [comment]
Is this change going to get merged in soon? 😄

**Comment by agilgur5** [comment]
> so official internal TS support is planned for the v1.1.x release of `react-signature-canvas`, at which point `@types/react-signature-canvas` will no longer be necessary

[`v1.1.0-alpha.1`](https://github.com/agilgur5/react-signature-canvas/releases/tag/v1.1.0-alpha.1) has been released as the first official native TS release
