### ISSUE TITLE
getTrimmedCanvas seem's not working

### ISSUE THREAD

**Issue by tracy-ridwan** [agilgur5/react-signature-canvas#22]
Hi i kinda try the example code. Everything work fine. But when i tried to get the trimmed version
why is it still giving me the original one?
```
console.log(this.sigPad.getTrimmedCanvas().toDataURL('image/png'));
console.log(this.sigPad.toDataURL('image/png'));
```

the base64 string for both command it's giving me the same string
am i missing something? thanks

**Comment by tracy-ridwan** [comment]
Hi gonna closed this one..
just realised that you should put any background color on canvas to be able to use the getTrimmedCanvas() function

**Comment by agilgur5** [comment]
I see, thanks for reporting the issue and investigating the cause. Yes, if you're using the `backgroundColor` prop (as opposed to the `background-color` CSS style), it [will fill the canvas context with a rectangle of that color](https://github.com/szimek/signature_pad/blob/master/src/signature_pad.ts#L108). Depending on your use case, you might just be able to use a CSS style instead which would not have the same issue as it doesn't draw anything on the canvas.

[agilgur5/trim-canvas](https://github.com/agilgur5/trim-canvas) currently only trims out [pure white sections](https://github.com/agilgur5/trim-canvas/blob/master/index.es6#L58) of the canvas and doesn't take any arguments. You can file an issue or submit a PR there for support for trimming out different colors if you'd like and that functionality is important to you.
