### ISSUE TITLE
Signature Pad does not follow cursor

### ISSUE THREAD

**Issue by MauriPastorini** [agilgur5/react-signature-canvas#28]
When I make use Chrome Dev tools to use size of a mobile, the signature pad doesnt follow the cursor of the mouse. I saw something like 
`canvasResize() {
    let canvas = document.querySelector('canvas');
    this.signaturePad.set('minWidth', 1);
    this.signaturePad.set('canvasWidth', canvas.offsetWidth);
    this.signaturePad.set('canvasHeight', canvas.offsetHeight);
  }`

But I cant get it to work

**Comment by agilgur5** [comment]
Can't reproduce this. Here's a video of me using the demo link, opening Dev Tools, re-sizing the screen and the cursor is still following totally normally: https://www.loom.com/share/0bffa22d40da45b4ae3d6c77acdcf8b3

Additionally, the code you wrote here does not seem to be for this library as that's not how you change the properties with this library, you use React props, and resizing is handled automatically with this library. I think you may have mistaken this library with some other one...

The de-sync you're talking about occurs when you don't clear the canvas on resize. It's detailed in this issue: https://github.com/agilgur5/react-signature-canvas/pull/2#issuecomment-310922701 . The solution is to either use the built-in default (`clearOnResize`, no changes required, it is the default behavior), or to use the workaround lopis described in that comment and in his new example in his PR: https://github.com/agilgur5/react-signature-canvas/pull/9

If you can reproduce this with this library, please provide a screencapture of it at the demo site and the steps you took to reproduce it.

**Comment by agilgur5** [comment]
This issue is quite stale and invalid, but if anyone stumbles upon this in the future, the canvas de-sync issue is actually native to the canvas element itself and I described it in more detail in #43 (where I've been referring duplicates to).
