### ISSUE TITLE
setting clearOnCanvas props to false

### ISSUE THREAD

**Issue by narxiss24** [agilgur5/react-signature-canvas#30]
Hi! I am trying to set clearOnResize to false, because my canvas pops out as a modal, and the screen resizes itself every time the modal is initiated, clearing the canvas. Can't seen to get clearOnResize = false working. Am I passing the props for clearOnResize correctly? Thanks

`<div className="drawing-canvas">
                            <SignatureCanvas
                              clearOnResize={false}
                              minWidth={0.9}
                              maxWidth={0.9}
                              canvasProps={{
                                width: size.width,
                                height: size.width * 1.2941,
                                className: "sigCanvas"
                              }}
                              ref={ref => {
                                this.sigPad = ref;
                              }}
                            />
                          </div>`

**Comment by agilgur5** [comment]
Can't reproduce this. Here's a video of me using the [demo link](https://agilgur5.github.io/react-signature-canvas/), opening React DevTools, setting `clearOnResize` to `false`, and it not being cleared when I change the screen size: 
https://www.loom.com/share/38564e9a4a7a43088631628ede797279

Based on your _not relevant_ PR in #29 , you might be using the wrong library to begin with.

If you can reproduce this with this library, please provide either a:
- a CodeSandbox example (or equivalent) or
- a screencapture of it at the demo site and the steps you took to reproduce it

**Comment by narxiss24** [comment]
Thanks for the video! Clearly it worked well in your video, I will figure out why mine didn't work and let you know if I can reproduce. I am using your library. Sorry for the mistake in the PR earlier, a newbie, what I wanted to do was to get your version of the library. got that sorted out, thanks!

**Comment by liljosi** [comment]
I clicked on your demo because i'm having the same issue and it's actually clearing on resize too.
