### ISSUE TITLE
How can Upload as image file?

### ISSUE THREAD

**Issue by whitesnow9291** [agilgur5/react-signature-canvas#35]
After drawing, how can it be append to formdata?

**Comment by agilgur5** [comment]
Ah, good usage question! There's a small bit about this in [`signature_pad`'s README](https://github.com/szimek/signature_pad#handling-data-uri-encoded-images-on-the-server-side), but it doesn't go too into detail.

To begin, you could upload the image as a blob, or you could upload it as a dataURL (the above link goes over how you might decode a dataURL server-side). As a dataURL, it's just a very long string, so sending that to the server is, for the most part, like `POST`ing any other string.

As a blob, yes you can use [`FormData`](https://developer.mozilla.org/en-US/docs/Web/API/FormData) for that. To get the blob, you'll have to get the raw [`Canvas` element](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement) from a `ref` to `react-signature-canvas`. For instance, if you're using class components and your ref is stored in `this.sigCanvas` like some of the examples, you would use:

```javascript
const canvas = this.sigCanvas.getCanvas()
```

Once you've got the `canvas`, one option to transform it into a blob is through the [`canvas.toBlob`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob) function. It's important to note that `toBlob` is [not supported in all browsers](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob#Browser_compatibility), so you might want to polyfill it with something like [`blueimp-canvas-to-blob`](https://www.npmjs.com/package/blueimp-canvas-to-blob) depending on what type of users you need to support. With `toBlob`, you can then do:

```javascript
canvas.toBlob((blob) => {
  const fd = new window.FormData()
  fd.append('signature', blob, 'signature.png')
  // POST to server with your preferred requests library
})
```

`blueimp-canvas-to-blob` also exports [`dataURLtoBlob`](https://www.npmjs.com/package/blueimp-canvas-to-blob#api), so if you were to use that polyfill/library and that function, you could also do:

```javascript
import dataURLtoBlob from 'blueimp-canvas-to-blob'

// ...

const blob = dataURLtoBlob(canvas.toDataURL('image/png'))
const fd = new window.FormData()
fd.append('signature', blob, 'signature.png')
// POST to server with your preferred requests library
```

There's of course other ways of doing it, but hope those examples help or point you in the right direction at least 🙂
