### ISSUE TITLE
Won't draw when Pointer Lock activated

### ISSUE THREAD

**Issue by liljosi** [agilgur5/react-signature-canvas#40]
After implementing pointer locker on canvas you can't draw anymore, trying to focus on the canvas because i'm trying to capture input from a drawing pad, the reason being that without pointer locker the user is everywhere on screen.

**Comment by agilgur5** [comment]
This is the first time I've heard of the [Pointer Lock API](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API), so can't say I'll be too helpful with this, but I'll give it a try.

Have you tried calling `requestPointerLock()` inside of an `onBegin` callback? That way it would ensure that `signature_pad` has received the pointer event already, vs. if you added a second `onclick` callback, it might occur before it received the event (I'm not sure if the order actually matters though? again, inexperienced with this API). Would be good to have a reproduction.

> the reason being that without pointer locker the user is everywhere on screen

I'm not sure what you mean by this. In the demos for [`react-signature-canvas`](https://agilgur5.github.io/react-signature-canvas/) and for [`signature_pad`](http://szimek.github.io/signature_pad/), this is not the case. This may just be an issue with your specific set-up.

In any case, the pointer event handling in `react-signature-canvas` is [entirely deferred to `signature_pad`](https://github.com/agilgur5/react-signature-canvas/blob/d449c18b5d3b7e3bda22bdafcc7e9ddba9e51cd7/src/index.js#L110), so if there is some bug, it is an upstream one.

While we can do some potential fixes or workarounds here, such bugs should generally be resolved upstream.
