### ISSUE TITLE
Width and Height change

### ISSUE THREAD

**Issue by liljosi** [agilgur5/react-signature-canvas#41]
If you change the height and width using a css class it just zooms in the canvas and the pointer is defaced, but when you change it using the width and height props it works correctly, but clears the canvas every time i change the size when i implement a onMouseOver and onMouseOut.

**Comment by agilgur5** [comment]
> If you change the height and width using a css class it just zooms in the canvas and the pointer is defaced

I'm not sure what you mean by "pointer is defaced", the demo uses a CSS class and does not set `width` or `height` props. CSS does [scale the rendered area](https://www.kirupa.com/html5/resizing_html_canvas_element.htm), but this is not necessarily problematic. I don't know how you're using it, as you did not provide a reproduction.
If you're _changing_ the size though, that will _distort_ the Canvas; it's not really meant to be resized, as per the below

> clears the canvas every time i change the size

This is behavior of the Canvas API, and not specific to `react-signature-canvas`. When the canvas's size is changed, it clears all content [per the spec](https://html.spec.whatwg.org/multipage/canvas.html#attr-canvas-width), which states:

> When the user [...] sets [...] width and height, it must run these steps:
[...]
> - Resize the output bitmap to the new width and height and clear it to transparent black.

<hr> 

There is a `clearOnResize` prop in `react-signature-canvas`, but that is related to _window_ resizes, which does not seem to be the topic of your issue. You didn't include a reproduction though
