### ISSUE TITLE
Importing 'src/' with latest CRA errors gets syntax error

### ISSUE THREAD

**Issue by zhil** [agilgur5/react-signature-canvas#50]
Library cant be used with create-react-app by default because of error
![image](https://user-images.githubusercontent.com/981783/84013998-59767700-a982-11ea-8eaa-9d3fda9e337d.png)

@babel/plugin-proposal-class-properties cant be added without ejecting CRA, which is pain.
CRA explanations
![image](https://user-images.githubusercontent.com/981783/84014615-4b752600-a983-11ea-916e-3d27ea8566bb.png)
![image](https://user-images.githubusercontent.com/981783/84014731-7b242e00-a983-11ea-93e3-51ed012398cd.png)

Not sure how to fix it, is it possible to change that experemental syntax?

related issues
https://github.com/facebook/create-react-app/issues/4648
https://github.com/material-components/material-components-web-react/issues/107

**Comment by zhil** [comment]
ok, I tried to use another CRA version, which I supposed to have that babel plugin enabled - because your library works fine for me in another project.
But it failed with the same error.

And I noticed, that in other project I have
```
import SignatureCanvas from "react-signature-canvas/src";
```

and in current project autocompletion added
```
import SignatureCanvas from "react-signature-canvas";
```

So issue is solved for me. Not sure about all that "experemental syntax" stuff - probably, we could close this issue if its false error.

**Comment by agilgur5** [comment]
Yea you imported `src/`, which as you might imagine, contains untranspiled source code. If you import regularly, you'll get the transpiled code.

`src/` is really only there to aid in debugging along with the sourcemaps, and not to be imported directly in code.
