### ISSUE TITLE
Material-UI integration example Gist

### ISSUE THREAD

**Issue by yanickrochon** [agilgur5/react-signature-canvas#59]
Just wanted to leave [this here](https://gist.github.com/yanickrochon/0d5c41a03ed1a8bef4c47140400bb802), perhaps someone will find it useful, or create project out of it.

![image](https://user-images.githubusercontent.com/78461/99399325-82951f00-28b3-11eb-9d16-6d9f177393ba.png)

**Comment by agilgur5** [comment]
Thanks for providing an example. Planning to create a Storybook for these at some point
