### ISSUE TITLE
Bug with `toDataURL` and device pixel ratios > 1

### ISSUE THREAD

**Issue by buesing** [agilgur5/react-signature-canvas#63]
When serializing the canvas data with `toDataURL` and then again de-serializing the same data with `fromDataURL`, the canvas content is not scaled correctly on device with a device pixel ratio larger than 1. The drawing is duplicated in the top left corner, scaled down:
![image](https://user-images.githubusercontent.com/1181371/133975531-ad1e7d8a-1077-45ee-8f8f-36ae6bdf114a.png)

Here is a repro sandbox: https://codesandbox.io/s/elated-cookies-50yg2?file=/src/App.js
Try it on a device with pixel ratio 1, works fine, but on a retina screen or iphone you can observe the effect above. You can even use the iPhone emulator in chrome desktop.

**Comment by buesing** [comment]
My bad, the solution is described here https://github.com/szimek/signature_pad#handling-high-dpi-screens

**Comment by agilgur5** [comment]
Yup, those are the relevant docs for DPR scaling. This also duplicates #6
