### ISSUE TITLE
How to check if a dataURL is empty?

### ISSUE THREAD

**Issue by momolly1024** [agilgur5/react-signature-canvas#67]
Hi :)
Dose any way to check if image is empty ? 
First I try to 

```js
let str = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAAtJREFUGFdjYAACAAAFAAGq1chRAAAAAElFTkSuQmCC";
console.log( image === str )
```
It can work on my local , but not work for other computer .

So, i wonder if there have another solution.

Thanks.

**Comment by agilgur5** [comment]
I'm not sure what you mean by "image" in this context.

## `isEmpty()` method

If you mean checking if the signature canvas is empty, there is already a method for that, [`isEmpty()`](https://github.com/agilgur5/react-signature-canvas#api).

## dataURL may not be possible, `canvas` is, but is out-of-scope

### dataURL

If you mean checking if a dataURL is empty as you do in your code sample, I'm not sure if that is even possible. A quick search finds [this unanswered SO question](https://stackoverflow.com/q/28338211/3431180). 

> It can work on my local , but not work for other computer .

I've done some dataURL computation before, and indeed, if I recall correctly, an empty canvas has a different dataURL on different browsers. Similar to my research for #49 , I believe this depends on the browser's implementation of the canvas, which will differ.

### `canvas`

If you're not using `isEmpty()` and want to check if a canvas _element_ is empty, here's [an SO answer](https://stackoverflow.com/a/17386803/3431180) with a few different ways of checking if a canvas is empty.
[`trim-canvas`](https://github.com/agilgur5/trim-canvas) (used by this library for `.getTrimmedCanvas()` and also maintained by me) implements [some similar logic](https://github.com/agilgur5/trim-canvas/blob/e2e607362cf5657d240aab6ddf1f6d35717f2822/src/index.js#L70) as one of the ways in that SO answer.

In any case, either computation on a raw dataURL or on a raw `canvas` element is out-of-scope for this library, which maintains a signature API specifically and already implements `isEmpty()` for signatures as per my first paragraph.
