### ISSUE TITLE
Custom CSS properties? (for custom cursor etc)

### ISSUE THREAD

**Issue by l4b4r4b4b4** [agilgur5/react-signature-canvas#78]
Is it possible to set a custom cursor as well as other css properties for the SignatureCanvas element? If so, how?

Help would be highly appreciated :)

**Comment by agilgur5** [comment]
Yes, per the README this is just a tiny, unopinionated wrapper around a `<canvas />` element.

Anything passed to the [`canvasProps` prop](https://github.com/agilgur5/react-signature-canvas#props) will be passed directly to the underlying [`<canvas />`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas) element's props.

The ["Usage" section](https://github.com/agilgur5/react-signature-canvas#usage) also shows an example of your use-case by passing a `className` through, as does [the official example](https://github.com/agilgur5/react-signature-canvas/blob/b14060c4cf8e40cbd8f54fee830d4b6b680f007a/example/src/index.js#L27).
You can also pass an inline style by passing a [`style` prop](https://reactjs.org/docs/dom-elements.html#style) as you can do with any React DOM elements.
