### ISSUE TITLE
`TypeError: sigCanvas.current.getTrimmedCanvas is not a function`

### ISSUE THREAD

**Issue by pneha2296** [agilgur5/react-signature-canvas#91]
![image](https://user-images.githubusercontent.com/63401708/190562286-524e5b5f-f9a4-4928-89d3-3f8bfb5d45d5.png)
![image](https://user-images.githubusercontent.com/63401708/190562319-42ef88d8-afae-4997-b464-ab912b391a07.png)

my code is:

```jsx
<SignaturePad
  ref={sigCanvas}
  // inputRef={ref}
  canvasProps={{
    className: "h-48 w-full border border-black bg-white",
  }}
  id={`${list?.id}`}
  {...register(`${list?.id}`, {
     required: false,
     onChange: (e) => handleFileSelect(e, list?.id),
   })}
/>
<label
  htmlFor={`${list?.id}`}
  onClick={() => {
    const url = sigCanvas.current.getTrimmedCanvas().toDataURL("image/png")
    onClickSignatureUpload(url, list?.id)
  }}
  className="cursor-pointer text-dark-reject"
> Save</label>
```

I used `label` to save image and it will throw error

**Comment by agilgur5** [comment]
Sorry, I can't reproduce this. All test pass, the demo, CodeSandbox, and other examples all work with `getTrimmedCanvas`.

> my code is:

This is just JSX and not even a full component. It is missing many pieces, such as how you create the ref, for instance. This is not useable as a reproduction.
Furthermore, much of the code you added here is not specific to `react-signature-canvas` and even adds props like `...register` that aren't related to this component.
I also had to fix various indentation issues in this code sample as well...

Please provide an actual, [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) or demo displaying this behavior, such as:
* a CodeSandbox example (or equivalent) or
* a screencapture of it at the demo site and the steps you took to reproduce it or
* a failing test case

> `TypeError: sigCanvas.current.getTrimmedCanvas is not a function`

That being said, this doesn't even seem to be a `react-signature-canvas` error, and rather, seems to be a React usage issue.
`getTrimmedCanvas` is not a function because `sigCanvas.current` does not exist / is `null`. Per the [React `ref` docs](https://reactjs.org/docs/refs-and-the-dom.html#accessing-refs), `ref.current` is `null` before mounting and after unmounting.

**Comment by pneha2296** [comment]
`import React, { Fragment, useCallback, useEffect, useRef, useState } from "react";

import { Tab } from "@headlessui/react";
import clsx from "clsx";
import _ from "lodash";
import { useForm } from "react-hook-form";
import toast from "react-hot-toast";
import { useDispatch } from "react-redux";
import { useNavigate, useParams } from "react-router-dom";
import Select from "react-select";
import SignaturePad from "react-signature-canvas";

import {
  GoogleDocsIcon,
  GoogleSheetsIcon,
  PdfIcon,
  StarIcon,
  XIcon,
} from "components/icons";
import { Button, Loading, Modal } from "components/ui";
import Progress from "components/ui/Progress";
import { ApplicationInfo } from "components/userDashboard";

import {
  applyApplication,
  retrieveApplicationById,
} from "actions/applications";
import { createSignedUrl, uploadFile } from "actions/fileUpload";
import { userSubscriptionCheck } from "actions/user";

import { bytesToSize } from "utils/calculateFileSize";

const MyApplication = () => {
  const dispatch = useDispatch();
  const navigate = useNavigate();
  const { applicationId } = useParams();
  const sigCanvas = useRef({});

  const [isLoading, setIsLoading] = useState(false);
  const [isApplyLoading, setIsApplyLoading] = useState(false);
  const [isHaveSub, setIsHaveSub] = useState(false);
  const [applicationDetails, setApplicationDetails] = useState({});
  const [applicationSideNav, setApplicationSideNav] = useState([]);
  const groups = _.groupBy(applicationDetails?.formBuilder, "mainTitle");
  const [fileUploadDeatisl, setFileUploadDeatisl] = useState([]);
  const uploadedFiles = [];

  const {
    register,
    handleSubmit,
    setValue,
    formState: { errors },
  } = useForm();

  const fetchApplicationDetails = useCallback(() => {
    setIsLoading(true);
    dispatch(retrieveApplicationById(applicationId))
      .then((response) => {
        setApplicationDetails(response);
        const groups = _.groupBy(response?.formBuilder, "mainTitle");
        let q = Object.keys(groups);
        setApplicationSideNav(q);
      })
      .catch((error) => {
        console.log(error, "Error while Fetching Application");
      })
      .finally(() => {
        setIsLoading(false);
      });
  }, [applicationId, dispatch]);

  const checkUserSubscription = useCallback(() => {
    dispatch(userSubscriptionCheck()).then((response) => {
      if (
        !(response.isSubscriptionActive || response.userCanCreateApplication)
      ) {
        setIsHaveSub(true);
      }
    });
  }, [dispatch]);

  //FOR SELECT TAG
  const selectOptions = (option) => {
    const mappedOptions = option.map((option) => {
      return { value: option, label: option };
    });
    return mappedOptions;
  };

  //GETING VALUE FROM SELECT TAG
  const selectedUsers = (event, id) => {
    const values = event.map((o) => o.value);
    setValue(`${id}`, values);
  };

  //FOR UPLOAD DOCUMENT

  //CREATING BODY FOR API
  const onBodyGenerate = (bodyData) => {
    const convertArry = Object.keys(bodyData).map(function (name) {
      const obj = {};
      obj[name] = bodyData[name];
      return obj;
    });
    let objectCreate = [];
    for (let i = 0; i < convertArry.length; i++) {
      const element = convertArry[i];
      const objectBody = {
        formBuilder: {
          id: Object.keys(element)[0],
        },
        answerText: Object.values(element)[0],
      };
      objectCreate.push(objectBody);
    }
    const body = {
      paymentId: "77c25deb-545b-4fc7-89c9-fabc450501ea",
      paymentMode: "card",
      amount: applicationDetails.price,
      departmentApplication: {
        id: applicationId,
      },
      details: objectCreate,
      isDraft: false,
    };
    return body;
  };

  //APPLYING FOR APPLICATION
  const onSubmit = handleSubmit((data) => {
    setIsApplyLoading(true);
    const body = onBodyGenerate(data);
    dispatch(applyApplication(body))
      .then((response) => {
        if (response.id !== null) {
          navigate("/applications");
        } else {
          toast.error("Application Failed!");
        }
      })
      .catch((error) => {
        console.log(error, "error apply application");
      })
      .finally(() => {
        setIsApplyLoading(false);
      });
  });

  const handleFileSelect = (e, id) => {
    let selectedFile = e.target.files[0];
    const size = bytesToSize(selectedFile?.size);
    if (size <= 30.0) {
      const body = {
        fileName: selectedFile?.name,
        mimeType: selectedFile?.type,
        directory: "document",
      };
      dispatch(createSignedUrl(body))
        .then((response) => {
          setValue(id, response?.s3Key);
          dispatch(uploadFile(response?.signedUrl, selectedFile));
        })
        .catch((error) => {
          console.log(error);
        })
        .finally(() => {
          const fileType = {
            title: selectedFile?.name,
            type: selectedFile?.type,
            size: selectedFile?.size,
            percentage: 100,
          };
          uploadedFiles.push(fileType);
          setFileUploadDeatisl(uploadedFiles);
        });
    } else {
      toast.error("Please select file size between 9.8kb to 15.0kb");
    }
  };

  const onClickSignatureUpload = (url, id) => {
    console.log("signature Upload start");
    fetch(url)
      .then(res => res.blob())
      .then(blob => {
        const file = new File([blob], "signature.png", { type: "image/png" });
        const body = {
          fileName: file?.name,
          mimeType: file?.type,
          directory: "document",
        };
        dispatch(createSignedUrl(body))
          .then((response) => {
            setValue(id, response?.s3Key);
            dispatch(uploadFile(response?.signedUrl, file));
          })
          .catch((error) => {
            console.log(error);
          })
          .finally(() => {
            const fileType = {
              title: file?.name,
              type: file?.type,
              size: file?.size,
              percentage: 100,
            };
            uploadedFiles.push(fileType);
            setFileUploadDeatisl(uploadedFiles);
          });
      })
  }

  useEffect(() => {
    fetchApplicationDetails();
    checkUserSubscription();
  }, [fetchApplicationDetails, checkUserSubscription]);

  if (isLoading) {
    return (
      <Loading className="fixed inset-0 flex h-full w-full items-center justify-center bg-transparent" />
    );
  } else {
    return (
      <>
        <section>
          <div className="bg-cornflower-blue">
            <Tab.Group>
              <div className="fixed inset-0 h-full w-80 overflow-y-auto bg-white px-6 pb-10 pt-20">
                <div>
                  <div className="mb-14 pt-5">
                    <img
                      src="/aurora-illinois.png"
                      alt="logo"
                      className="mx-auto h-16 object-cover"
                    />
                  </div>
                  <div>
                    <h3 className="mb-4 text-lg font-medium text-japanese-indigo">
                      Application Title
                    </h3>
                    <Tab.List
                      as="div"
                      className="flex w-full flex-col items-start divide-y divide-cadet-blue/30"
                    >
                      {applicationSideNav?.map((tab, i) => (
                        <div key={i} className="w-full">
                          <Tab
                            className={({ selected }) =>
                              clsx(
                                "inline-flex h-[60px] items-center border-l-4 px-5 outline-none",
                                selected
                                  ? "border-azure-radiance text-azure-radiance"
                                  : "border-transparent text-japanese-indigo"
                              )
                            }
                          >
                            <StarIcon className="mr-4" />
                            {tab}
                          </Tab>
                        </div>
                      ))}
                    </Tab.List>
                  </div>
                </div>
              </div>
              <div className="min-h-screen pl-80">
                <Tab.Panels>
                  {applicationSideNav?.map((tab, i) => (
                    <Tab.Panel key={i}>
                      <div className="min-h-screen">
                        <div className="px-4 pt-8 pb-28 sm:px-6 lg:px-8 lg:pb-8">
                          <ApplicationInfo />
                          <h3 className="my-8 text-2xl text-independence">
                            {applicationDetails?.title}
                          </h3>
                          <div className="grid grid-cols-1">
                            <div className="space-y-8 xl:col-span-3">
                              <div className="rounded bg-white p-8">
                                <h5 className="mb-8 text-lg capitalize text-independence">
                                  {tab}
                                </h5>
                                <div className="grid grid-cols-1 gap-5 xl:grid-cols-3">
                                  {Object(groups)
                                  [tab]?.sort((a, b) =>
                                    a?.priority > (b?.priority || b?.priority)
                                      ? 1
                                      : -1
                                  )
                                    ?.map((list, index) => {
                                      return (
                                        <form key={index} onSubmit={onSubmit}>
                                          <div className="col-span-2 flex flex-col">
                                            <label className="mb-1 text-independence">
                                              {list?.inputName}
                                            </label>
                                            {list.inputType.type === "text" && (
                                              <>
                                                <input
                                                  type={list?.inputType?.type}
                                                  className="w-full rounded border-none bg-cornflower-blue placeholder:font-light placeholder:text-[#999696] focus:ring-0"
                                                  name={`${list?.id}`}
                                                  {...register(`${list?.id}`, {
                                                    required: true,
                                                  })}
                                                />
                                                {errors?.[list?.id] && (
                                                  <p className="flex justify-end text-sm text-[#CC3300]">
                                                    This field is required
                                                  </p>
                                                )}
                                              </>
                                            )}
                                            {list.inputType.type ===
                                              "password" && (
                                                <>
                                                  <input
                                                    type={list?.inputType?.type}
                                                    className="w-full rounded border-none bg-cornflower-blue placeholder:font-light placeholder:text-[#999696] focus:ring-0"
                                                    name={`${list?.id}`}
                                                    {...register(`${list?.id}`, {
                                                      required: true,
                                                    })}
                                                  />
                                                  {errors?.[list?.id] && (
                                                    <p className="flex justify-end text-sm text-[#CC3300]">
                                                      This field is required
                                                    </p>
                                                  )}
                                                </>
                                              )}
                                            {list.inputType.type ===
                                              "number" && (
                                                <>
                                                  <input
                                                    type={list?.inputType?.type}
                                                    className="w-full rounded border-none bg-cornflower-blue placeholder:font-light placeholder:text-[#999696] focus:ring-0"
                                                    name={`${list?.id}`}
                                                    {...register(`${list?.id}`, {
                                                      required: true,
                                                    })}
                                                  />
                                                  {errors?.[list?.id] && (
                                                    <p className="flex justify-end text-sm text-[#CC3300]">
                                                      This field is required
                                                    </p>
                                                  )}
                                                </>
                                              )}
                                            {list.inputType.type ===
                                              "email" && (
                                                <>
                                                  <input
                                                    type={list?.inputType?.type}
                                                    className="w-full rounded border-none bg-cornflower-blue placeholder:font-light placeholder:text-[#999696] focus:ring-0"
                                                    name={`${list?.id}`}
                                                    {...register(`${list?.id}`, {
                                                      required: true,
                                                    })}
                                                  />
                                                  {errors?.[list?.id] && (
                                                    <p className="flex justify-end text-sm text-[#CC3300]">
                                                      This field is required
                                                    </p>
                                                  )}
                                                </>
                                              )}
                                            {list.inputType.type === "tel" && (
                                              <>
                                                <input
                                                  type={list?.inputType?.type}
                                                  className="w-full rounded border-none bg-cornflower-blue placeholder:font-light placeholder:text-[#999696] focus:ring-0"
                                                  name={`${list?.id}`}
                                                  {...register(`${list?.id}`, {
                                                    required: true,
                                                  })}
                                                />
                                                {errors?.[list?.id] && (
                                                  <p className="flex justify-end text-sm text-[#CC3300]">
                                                    This field is required
                                                  </p>
                                                )}
                                              </>
                                            )}
                                            {list.inputType.type === "url" && (
                                              <>
                                                <input
                                                  type={list?.inputType?.type}
                                                  className="w-full rounded border-none bg-cornflower-blue placeholder:font-light placeholder:text-[#999696] focus:ring-0"
                                                  name={`${list?.id}`}
                                                  {...register(`${list?.id}`, {
                                                    required: true,
                                                  })}
                                                />
                                                {errors?.[list?.id] && (
                                                  <p className="flex justify-end text-sm text-[#CC3300]">
                                                    This field is required
                                                  </p>
                                                )}
                                              </>
                                            )}
                                            {list.inputType.type ===
                                              "search" && (
                                                <>
                                                  <input
                                                    type={list?.inputType?.type}
                                                    className="w-full rounded border-none bg-cornflower-blue placeholder:font-light placeholder:text-[#999696] focus:ring-0"
                                                    name={`${list?.id}`}
                                                    {...register(`${list?.id}`, {
                                                      required: true,
                                                    })}
                                                  />
                                                  {errors?.[list?.id] && (
                                                    <p className="flex justify-end text-sm text-[#CC3300]">
                                                      This field is required
                                                    </p>
                                                  )}
                                                </>
                                              )}
                                            {list.inputType.type ===
                                              "datetime-local" && (
                                                <>
                                                  <input
                                                    type={list?.inputType?.type}
                                                    className="w-full rounded border-none bg-cornflower-blue placeholder:font-light placeholder:text-[#999696] focus:ring-0"
                                                    name={`${list?.id}`}
                                                    {...register(`${list?.id}`, {
                                                      required: true,
                                                    })}
                                                  />
                                                  {errors?.[list?.id] && (
                                                    <p className="flex justify-end text-sm text-[#CC3300]">
                                                      This field is required
                                                    </p>
                                                  )}
                                                </>
                                              )}
                                            {list.inputType.type === "time" && (
                                              <>
                                                <input
                                                  type={list?.inputType?.type}
                                                  className="w-full rounded border-none bg-cornflower-blue placeholder:font-light placeholder:text-[#999696] focus:ring-0"
                                                  name={`${list?.id}`}
                                                  {...register(`${list?.id}`, {
                                                    required: true,
                                                  })}
                                                />
                                                {errors?.[list?.id] && (
                                                  <p className="flex justify-end text-sm text-[#CC3300]">
                                                    This field is required
                                                  </p>
                                                )}
                                              </>
                                            )}
                                            {list.inputType.type === "week" && (
                                              <>
                                                <input
                                                  type={list?.inputType?.type}
                                                  className="w-full rounded border-none bg-cornflower-blue placeholder:font-light placeholder:text-[#999696] focus:ring-0"
                                                  name={`${list?.id}`}
                                                  {...register(`${list?.id}`, {
                                                    required: true,
                                                  })}
                                                />
                                                {errors?.[list?.id] && (
                                                  <p className="flex justify-end text-sm text-[#CC3300]">
                                                    This field is required
                                                  </p>
                                                )}
                                              </>
                                            )}
                                            {list.inputType.type ===
                                              "month" && (
                                                <>
                                                  <input
                                                    type={list?.inputType?.type}
                                                    className="w-full rounded border-none bg-cornflower-blue placeholder:font-light placeholder:text-[#999696] focus:ring-0"
                                                    name={`${list?.id}`}
                                                    {...register(`${list?.id}`, {
                                                      required: true,
                                                    })}
                                                  />
                                                  {errors?.[list?.id] && (
                                                    <p className="flex justify-end text-sm text-[#CC3300]">
                                                      This field is required
                                                    </p>
                                                  )}
                                                </>
                                              )}
                                            {list.inputType.type ===
                                              "datetime" && (
                                                <>
                                                  <input
                                                    type="date"
                                                    className="w-full rounded border-none bg-cornflower-blue placeholder:font-light placeholder:text-[#999696] focus:ring-0"
                                                    name={`${list?.id}`}
                                                    {...register(`${list?.id}`, {
                                                      required: true,
                                                    })}
                                                  />
                                                  {errors?.[list?.id] && (
                                                    <p className="flex justify-end text-sm text-[#CC3300]">
                                                      This field is required
                                                    </p>
                                                  )}
                                                </>
                                              )}
                                            {list?.inputType?.type ===
                                              "range" && (
                                                <>
                                                  <input
                                                    type={list?.inputType?.type}
                                                    className="w-full rounded border-none bg-cornflower-blue placeholder:font-light placeholder:text-[#999696] focus:ring-0"
                                                    name={`${list?.id}`}
                                                    {...register(`${list?.id}`, {
                                                      required: true,
                                                    })}
                                                  />
                                                  {errors?.[list?.id] && (
                                                    <p className="flex justify-end text-sm text-[#CC3300]">
                                                      This field is required
                                                    </p>
                                                  )}
                                                </>
                                              )}
                                            {list?.inputType?.type ===
                                              "select" && (
                                                <>
                                                  <select
                                                    className="w-full rounded border-none bg-cornflower-blue font-light text-independence focus:border-none focus:ring-0"
                                                    {...register(`${list?.id}`, {
                                                      required: true,
                                                    })}
                                                  >
                                                    <option value="null">
                                                      Choose an option
                                                    </option>
                                                    {list?.option?.map(
                                                      (option, i) => {
                                                        return (
                                                          <option
                                                            key={i}
                                                            value={option}
                                                            selected
                                                          >
                                                            {option}
                                                          </option>
                                                        );
                                                      }
                                                    )}
                                                  </select>
                                                  {errors?.[list?.id] && (
                                                    <p className="flex justify-end text-sm text-[#CC3300]">
                                                      This field is required
                                                    </p>
                                                  )}
                                                </>
                                              )}
                                            {list?.inputType?.type ===
                                              "multiselect" && (
                                                <>
                                                  <Select
                                                    isMulti
                                                    options={selectOptions(
                                                      list?.option
                                                    )}
                                                    onChange={(e) =>
                                                      selectedUsers(e, list?.id)
                                                    }
                                                  // {...register(`${list?.id}`, { required: true })}
                                                  />
                                                  {errors?.[list?.id] && (
                                                    <p className="flex justify-end text-sm text-[#CC3300]">
                                                      This field is required
                                                    </p>
                                                  )}
                                                </>
                                              )}
                                            {list?.inputType?.type ===
                                              "checkbox" && (
                                                <>
                                                  <Fragment>
                                                    <div className="grid grid-cols-2 gap-5">
                                                      {list?.option?.map(
                                                        (option, i) => {
                                                          return (
                                                            <div key={i}>
                                                              <input
                                                                type="checkbox"
                                                                id={`${list?.id}.${i}`}
                                                                name={`${list?.id}`}
                                                                value={option}
                                                                className="mr-2"
                                                                {...register(
                                                                  `${list?.id}`,
                                                                  {
                                                                    required: true,
                                                                  }
                                                                )}
                                                              />
                                                              <label
                                                                className="capitalize"
                                                                htmlFor={`${list?.id}.${i}`}
                                                              >
                                                                {option}
                                                              </label>
                                                            </div>
                                                          );
                                                        }
                                                      )}
                                                    </div>
                                                  </Fragment>
                                                  {errors?.[list?.id] && (
                                                    <p className="flex justify-end text-sm text-[#CC3300]">
                                                      This field is required
                                                    </p>
                                                  )}
                                                </>
                                              )}
                                            {list.inputType.type ===
                                              "radio" && (
                                                <Fragment>
                                                  <div className="grid grid-cols-2 gap-5">
                                                    {list?.option?.map(
                                                      (option, i) => {
                                                        return (
                                                          <div key={i}>
                                                            <input
                                                              id={`${list?.id}.${option}`}
                                                              type="radio"
                                                              className="mr-2"
                                                              value={option}
                                                              {...register(
                                                                `${list?.id}`,
                                                                { required: true }
                                                              )}
                                                            />
                                                            <label
                                                              htmlFor={`${list.id}.${option}`}
                                                              className="capitalize"
                                                            >
                                                              {option}
                                                            </label>
                                                          </div>
                                                        );
                                                      }
                                                    )}
                                                  </div>
                                                  {errors?.[list?.id] && (
                                                    <p className="flex justify-end text-sm text-[#CC3300]">
                                                      This field is required
                                                    </p>
                                                  )}
                                                </Fragment>
                                              )}
                                            {list.inputType.type ===
                                              "textarea" && (
                                                <>
                                                  <textarea
                                                    className="w-full resize-none rounded border-none bg-cornflower-blue font-light text-independence focus:border-none focus:ring-0"
                                                    name={`${list?.id}`}
                                                    {...register(`${list?.id}`, {
                                                      required: true,
                                                    })}
                                                  />
                                                  {errors?.[list?.id] && (
                                                    <p className="flex justify-end text-sm text-[#CC3300]">
                                                      This field is required
                                                    </p>
                                                  )}
                                                </>
                                              )}
                                            {list.inputType.type === "signature" && (
                                              <>
                                                <SignaturePad
                                                  ref={sigCanvas}
                                                  // inputRef={ref}
                                                  canvasProps={{
                                                    className:
                                                      "h-48 w-full border border-dashed border-independence bg-white",
                                                  }}
                                                  id={`${list?.id}`}
                                                  onChange={
                                                    (e) =>
                                                      handleFileSelect(
                                                        e,
                                                        list?.id
                                                      )
                                                  }
                                                />
                                                <div className="flex justify-center space-x-3 mt-6">
                                                  <Button
                                                    type="button"
                                                    width="28"
                                                    outlined
                                                    onClick={() => {
                                                      sigCanvas.current.clear();
                                                    }}>
                                                    Clear
                                                  </Button>
                                                  <Button
                                                    type="button"
                                                    width="36"
                                                    onClick={() => {
                                                      if (!sigCanvas.current.isEmpty()) {
                                                        const url = sigCanvas.current.getTrimmedCanvas().toDataURL("image/png")
                                                        onClickSignatureUpload(url, list?.id)
                                                      }
                                                    }}>
                                                    Save Signature
                                                  </Button>
                                                </div>
                                              </>

                                            )}
                                            {list.inputType.type === "file" && (
                                              <>
                                                <div className="rounded bg-white p-8">
                                                  <div className="mb-3 text-sm font-light text-cadet-blue">
                                                    Upload documents you want to
                                                    attached
                                                  </div>
                                                  <div className="mb-2 h-28 items-center justify-center rounded border border-dashed border-[#cecee2] bg-cornflower-blue text-independence sm:flex">
                                                    <label
                                                      htmlFor={`${list?.id}`}
                                                      className="cursor-pointer"
                                                    >
                                                      <input
                                                        className="hidden"
                                                        type="file"
                                                        id={`${list?.id}`}
                                                        {...register(
                                                          `${list?.id}`,
                                                          {
                                                            required: false,
                                                            onChange: (e) =>
                                                              handleFileSelect(
                                                                e,
                                                                list?.id
                                                              ),
                                                          }
                                                        )}
                                                        multiple
                                                      // onChange={(e) => handleFileSelect(e, list?.id)}
                                                      />
                                                      <div className="text-center font-light">
                                                        <span
                                                          className="font-normal text-azure-radiance"
                                                          htmlFor={`${list?.id}`}
                                                        >
                                                          Select Files
                                                        </span>
                                                      </div>
                                                    </label>
                                                  </div>
                                                  {errors?.[list?.id] && (
                                                    <p className="flex justify-end text-sm text-[#CC3300]">
                                                      This field is required
                                                    </p>
                                                  )}
                                                </div>
                                              </>
                                            )}
                                          </div>
                                        </form>
                                      );
                                    })}
                                </div>
                              </div>
                              {/* IF FILE UPLOAD */}
                              {fileUploadDeatisl.length !== 0 && (
                                <div className="rounded bg-white p-8">
                                  <div className="mb-3 text-sm font-light text-cadet-blue">
                                    Uploaded files
                                  </div>
                                  <div className="space-y-4">
                                    {fileUploadDeatisl.map((file, i) => {
                                      return (
                                        <div
                                          key={i}
                                          className="flex h-14 items-center justify-between rounded px-4 hover:shadow-[0_6.25px_16px_rgba(0,0,0,0.085)]"
                                        >
                                          <div className="flex w-full items-center">
                                            <div className="mr-2">
                                              {file.type ===
                                                "application/pdf" && (
                                                  <PdfIcon />
                                                )}
                                              {file.type ===
                                                "application/docs" && (
                                                  <GoogleDocsIcon />
                                                )}
                                              {file.type === "image/png" && (
                                                <GoogleSheetsIcon />
                                              )}
                                            </div>
                                            <div className="w-full">
                                              <div>{file.title}</div>
                                              <Progress
                                                percentage={file.percentage}
                                              />
                                              <div className="font-light text-cadet-blue">
                                                {file.size} KB
                                              </div>
                                            </div>
                                          </div>
                                          <div className="ml-2">
                                            <button className="inline-flex h-4 w-4 items-center justify-center rounded-full bg-[#E4E9FE]">
                                              <XIcon className="text-[#ABB4DE]" />
                                            </button>
                                          </div>
                                        </div>
                                      );
                                    })}
                                  </div>
                                </div>
                              )}
                              {applicationSideNav.length === i + 1 && (
                                <div className="flex w-full justify-center">
                                  <Button
                                    loading={isApplyLoading}
                                    onClick={onSubmit}
                                  >
                                    Save
                                  </Button>
                                </div>
                              )}
                            </div>
                          </div>
                        </div>
                      </div>
                    </Tab.Panel>
                  ))}
                </Tab.Panels>
              </div>
            </Tab.Group>
          </div>
        </section >

        <Modal
          title=""
          show={isHaveSub}
          onClose={() => setIsHaveSub(true)}
          onCancel={() => setIsHaveSub(true)}
        >
          <h2 className="my-3 mx-auto max-w-xs text-center text-lg font-medium capitalize">
            Hey there!
          </h2>
          <h2 className="my-3 mx-auto max-w-xs text-center text-lg font-medium capitalize">
            Looks like your free trial has been already expired
          </h2>
          <h2 className="my-3 mx-auto max-w-xs text-center text-lg font-medium capitalize">
            But do not worry, buy our subscription plans to continue the process
            efficiently
          </h2>
          <div className="my-7 flex">
            <Button
              width="30"
              className="mx-auto"
              onClick={() => navigate("/subscription")}
            >
              Choose our plans
            </Button>
          </div>
        </Modal>
      </>
    );
  }
};

export default MyApplication;`

![image](https://user-images.githubusercontent.com/63401708/190955091-3d8adea8-a5f1-485b-9eec-388f58b09d22.png)

here full code and version of package please solve issue then close it
