### ISSUE TITLE
Background Image lost while converting `toData` and back with `fromData` ("undo" operation)

### ISSUE THREAD

**Issue by nikhil478** [agilgur5/react-signature-canvas#93]
i was trying to render image in background of canvas by using canvas `.fromDataUrl()` func it is properly working
after using pen on canvas i want a option  to revert last operation 

so what i am trying to do is basically converting canvasObject to Data array and pop and then back to canvasObject code was something like this 

```js
undoCanvas = () => {
  let data = canvasRef.toData();
  if (data.length > 0) {
    data.pop();
  }
  canvasRef.fromData(data);
}
```

**Comment by agilgur5** [comment]
Per this project's description, `react-signature-canvas` is merely a wrapper component around [`signature_pad`](https://github.com/szimek/signature_pad).
Any activity that uses the `ref` is behavior that is provided by `signature_pad` and not specific to `react-signature-canvas`.
So your issue belongs upstream in `signature_pad`'s repo, and not here.

That being said, this does not seem like a bug and seems more like a support request.
`toData` only returns the point and curve information of your drawing ("pen"). That contains detailed, SVG-like vector data of for each click, drag, etc.
`fromDataUrl`, on the other hand, inserts a raster image onto the canvas. It's a single image; the dataUrl is merely a blob, and does not contain detailed point+curve information. This is briefly mentioned in `signature_pad`'s docs in [the example comments](https://github.com/szimek/signature_pad#api).
So `data` and `dataUrl` are distinct entities effectively, storing two different forms of information -- point+curve data vs. a blob of the whole canvas.

So if you want to use a background image, I might suggest an alternative method. For instance, as I recommended in https://github.com/agilgur5/react-signature-canvas/issues/60#issuecomment-1030713591, you could use [the CSS `background-image` property](https://developer.mozilla.org/en-US/docs/Web/CSS/background-image) instead.
This would have the benefit of being independent of and untied to the point+curve data, it'll just be consistently there.

**Comment by nikhil478** [comment]
@agilgur5 thanks for assistance and taking the time to help me !
