### ISSUE TITLE
Weird artifacts using Next.js 13

### ISSUE THREAD

**Issue by michaelbonner** [agilgur5/react-signature-canvas#95]
Some really bizarre things are happening while using Next.js 13. There's a dotted line from the top left of the canvas to where the cursor is drawing. 

Here's a reference image:

![Screenshot 2022-11-15 at 7 32 35 PM](https://user-images.githubusercontent.com/1122945/202069577-2511c71b-6d9f-442b-b2d0-a1138d185b56.png)

It only happens when using a production build. `npm run dev` works fine, but `npm run build` and `npm run start` makes the weirdness happen.

## Bare Bones Reproduction

repo:
https://github.com/michaelbonner/react-signature-pad-next-test

deployed URL:
https://react-signature-pad-next-test.vercel.app/

**Comment by vladshcherbin** [comment]
Same with another wrapper package - https://github.com/michaeldzjap/react-signature-pad-wrapper

I believe it's something with underlying `signature_pad` package and new [`SWC` compiler](https://nextjs.org/docs/advanced-features/compiler) which is ON by default in next 13.

**Comment by ElTimuro** [comment]
For everyone else: I was able to fix this by disabling swcMinify in the next config:

```
const nextConfig = {
  reactStrictMode: true,
  swcMinify: false,
};
```
