### ISSUE TITLE
What is the difference between SignaturePad and SignatureCanvas?

### ISSUE THREAD

**Issue by josh-thompson13** [agilgur5/react-signature-canvas#97]
As the title states, what is the difference?

Thanks :)

**Comment by agilgur5** [comment]
Please see the first few lines of the README that state this very explicitly:

> A React wrapper component around [signature_pad](https://github.com/szimek/signature_pad).
>
> Originally, this was just an _unopinionated_ fork of [react-signature-pad](https://github.com/blackjk3/react-signature-pad) that did not impose any styling or wrap any other unwanted elements around your canvas -- it's just a wrapper around a single canvas element! ...
